export const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;
export const SPOTIFY_CLIENT_ID = process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID;
export const SPOTIFY_CLIENT_SECRET =
  process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET;
export const SPOTIFY_REFRESH_TOKEN =
  process.env.NEXT_PUBLIC_SPOTIFY_REFRESH_TOKEN;
